//! Collection → curl / Rust codegen.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::Result;

use crate::collections::{Collection, SavedRequest};
use crate::http::AuthKind;

pub fn codegen_collection(col: &Collection, lang: &str, out_dir: &Path) -> Result<PathBuf> {
    fs::create_dir_all(out_dir)?;
    match lang {
        "rust" => {
            let path = out_dir.join(format!("{}_client.rs", sanitize(&col.name)));
            fs::write(&path, emit_rust(col))?;
            Ok(path)
        }
        _ => {
            let path = out_dir.join(format!("{}.sh", sanitize(&col.name)));
            fs::write(&path, emit_curl(col))?;
            Ok(path)
        }
    }
}

fn sanitize(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}

fn emit_curl(col: &Collection) -> String {
    let mut out = String::from("#!/usr/bin/env bash\nset -euo pipefail\n\n");
    for r in &col.requests {
        let method = r.method.as_deref().unwrap_or("GET");
        out.push_str(&format!("# {}\n", r.name));
        out.push_str(&format!("curl -sS -X {method}"));
        emit_curl_auth(&mut out, r);
        for (k, v) in &r.headers {
            out.push_str(&format!(
                " \\\n  -H '{}: {}'",
                k.replace('\'', ""),
                v.replace('\'', "")
            ));
        }
        if !r.body.is_empty() {
            out.push_str(&format!(
                " \\\n  --data-binary @- <<'EOF'\n{}\nEOF\n",
                r.body
            ));
            out.push_str(&format!("  '{}'\n\n", curl_target(r)));
        } else {
            out.push_str(&format!(" \\\n  '{}'\n\n", curl_target(r)));
        }
    }
    out
}

fn emit_curl_auth(out: &mut String, r: &SavedRequest) {
    match r.auth {
        AuthKind::None | AuthKind::ApiKeyQuery => {}
        AuthKind::Bearer | AuthKind::OAuth2 => {
            if !r.auth_token.is_empty() {
                out.push_str(&format!(
                    " \\\n  -H 'Authorization: Bearer {}'",
                    r.auth_token.replace('\'', "")
                ));
            }
        }
        AuthKind::Basic => {
            out.push_str(&format!(
                " \\\n  -u '{}:{}'",
                r.auth_user.replace('\'', ""),
                r.auth_pass.replace('\'', "")
            ));
        }
        AuthKind::ApiKeyHeader => {
            if !r.auth_key.is_empty() {
                out.push_str(&format!(
                    " \\\n  -H '{}: {}'",
                    r.auth_key.replace('\'', ""),
                    r.auth_value.replace('\'', "")
                ));
            }
        }
    }
}

fn curl_target(r: &SavedRequest) -> String {
    let mut target = r.target.clone();
    if r.auth == AuthKind::ApiKeyQuery && !r.auth_key.is_empty() {
        let sep = if target.contains('?') { '&' } else { '?' };
        target = format!(
            "{target}{sep}{}={}",
            r.auth_key,
            urlencoding::encode(&r.auth_value)
        );
    }
    target.replace('\'', "%27")
}

fn emit_rust(col: &Collection) -> String {
    let mut out = String::from(
        "// Generated by bitbeak codegen — AGPL-3.0-or-later\nuse reqwest::Client;\n\n",
    );
    out.push_str("pub async fn run_all() -> Result<(), Box<dyn std::error::Error>> {\n");
    out.push_str("    let client = Client::new();\n");
    for r in &col.requests {
        let method = r.method.as_deref().unwrap_or("GET").to_ascii_lowercase();
        let target = rust_target(r);
        out.push_str(&format!("    // {}\n", r.name));
        out.push_str(&format!(
            "    let _ = client.{method}(\"{}\")",
            target.replace('"', "\\\"")
        ));
        emit_rust_auth(&mut out, r);
        for (k, v) in &r.headers {
            out.push_str(&format!(
                "\n        .header(\"{}\", \"{}\")",
                k.replace('"', ""),
                v.replace('"', "\\\"")
            ));
        }
        if !r.body.is_empty() {
            out.push_str(&format!(
                "\n        .body(r#\"{}\"#)",
                r.body.replace("\"#", "\"\\#")
            ));
        }
        out.push_str("\n        .send().await?;\n");
    }
    out.push_str("    Ok(())\n}\n");
    out
}

fn rust_target(r: &SavedRequest) -> String {
    let mut target = r.target.clone();
    if r.auth == AuthKind::ApiKeyQuery && !r.auth_key.is_empty() {
        let sep = if target.contains('?') { '&' } else { '?' };
        target = format!("{target}{sep}{}={}", r.auth_key, r.auth_value);
    }
    target
}

fn emit_rust_auth(out: &mut String, r: &SavedRequest) {
    match r.auth {
        AuthKind::None | AuthKind::ApiKeyQuery => {}
        AuthKind::Bearer | AuthKind::OAuth2 => {
            if !r.auth_token.is_empty() {
                out.push_str(&format!(
                    "\n        .bearer_auth(\"{}\")",
                    r.auth_token.replace('"', "\\\"")
                ));
            }
        }
        AuthKind::Basic => {
            out.push_str(&format!(
                "\n        .basic_auth(\"{}\", Some(\"{}\"))",
                r.auth_user.replace('"', "\\\""),
                r.auth_pass.replace('"', "\\\"")
            ));
        }
        AuthKind::ApiKeyHeader => {
            if !r.auth_key.is_empty() {
                out.push_str(&format!(
                    "\n        .header(\"{}\", \"{}\")",
                    r.auth_key.replace('"', ""),
                    r.auth_value.replace('"', "\\\"")
                ));
            }
        }
    }
}

pub fn default_out_dir() -> PathBuf {
    PathBuf::from("bitbeak-out")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::collections::{Collection, SavedRequest};
    use crate::http::AuthKind;
    use tempfile::tempdir;

    #[test]
    fn emits_curl() {
        let mut col = Collection::new("demo");
        col.requests.push(SavedRequest {
            name: "ping".into(),
            kind: "http".into(),
            target: "https://example.com/".into(),
            method: Some("GET".into()),
            headers: vec![("Accept".into(), "*/*".into())],
            body: String::new(),
            auth: AuthKind::Bearer,
            auth_token: "secret".into(),
            ..Default::default()
        });
        let dir = tempdir().unwrap();
        let p = codegen_collection(&col, "curl", dir.path()).unwrap();
        let text = std::fs::read_to_string(p).unwrap();
        assert!(text.contains("curl"));
        assert!(text.contains("example.com"));
        assert!(text.contains("Authorization: Bearer secret"));
    }
}
